language: node_js
node_js:
    - "14.17.3"
script:
   - echo "deploying!"
install:
   - npm install -g firebase-tools
before_deploy: 'npm run build'
deploy:
  provider: firebase
  token:
    secure: secret
  project: secret
  skip_cleanup: true
after_success:
   - firebase deploy --token 1//0g3DXps58-8V8CgYIARAAGBASNwF-L9IrD5wNfL31thwvE58BxG6hKzWNaQD-eYxwan0Pc-1p-QrRz313LCdBvSS-4V42RXSeQhw
