language: node_js
node_js:
    - "14.17.3"
script:
   - echo "deploying!"
install:
   - npm install -g firebase-tools
after_success:
   - firebase deploy --token 1//0g3DXps58-8V8CgYIARAAGBASNwF-L9IrD5wNfL31thwvE58BxG6hKzWNaQD-eYxwan0Pc-1p-QrRz313LCdBvSS-4V42RXSeQhw
